### ISSUE TITLE
Welcome board - Antes de empezar

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#2]
> Si empiezas con esta tarea, pasa a la columna de "In progress"
:sparkles: **Antes de empezar** :sparkles:
¡Bienvenido equipo! Lo primero me presento, me llamo Alberto Muñoz Fuertes y soy vuestro **Tech Lead**, podéis contactar conmigo siempre que lo necesitéis y me agenda me lo permita ;) . Mis funciones actuales son:

- Decidir la tecnología a usar en el proyecto.
- Reunirme con el cliente y ayudarle en la decisiones a tomar.
- Revisar la calidad y progreso del proyecto.

Estoy muy contento porque al final la empresa ha decidido incluir a un nuevo equipo de desarrolladores, es decir vosotros. El proyecto tiene retrasos e identificamos este problema hace un mes.
Lo primero que necesitamos es que conozcáis nuestra forma de trabajar y en qué consiste el proyecto, para ello os dejamos un checklist de tareas previas que tendréis que hacer antes de ponernos "manos al código" :).

Podéis ver el video de presentación aquí:

[![Sesión 1 - Presentación](https://raw.githubusercontent.com/SalesianosZaragoza/ScrumEDD/master/cover1.jpg)](https://drive.google.com/file/d/1yePlThHwI6OaGTPDGoTWCyY4OcaBpAL-)

- [x] Tutorial 10 minutos SCRUM https://www.youtube.com/watch?v=PlLHc60egiQ 
- [x] Guía de principiantes para Scrum — 7 pasos: https://medium.com/forecast-en-espa%C3%B1ol/gu%C3%ADa-de-principiantes-para-scrum-7-pasos-127e30cfd585
- [x] Visual Studio Code: https://code.visualstudio.com/Download
- [x] Tutorial VS Code: https://www.youtube.com/watch?v=HVzFLw5r2EM
- [x] Política de código y su inclusión en el código final: https://www.atlassian.com/es/git/tutorials/making-a-pull-request

Documentación relativa al proyecto está disponible en el siguiente enlace, al ser un proyecto vivo la documentación está en constante evolución, es necesario que la reviséis cada cierto tiempo:
[WIKI](https://github.com/SalesianosZaragoza/ScrumEDD/wiki)

Lo dicho, bienvenido a bordo de la mejor empresa de desarrollo de Aragón.

Un saludo,
@slaptot

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

El Team5 hicimos una reunión inicial para organizarnos y aclarar dudas sobre las tareas.

¿Qué voy hacer hoy?

Todas las tareas asignadas de la primera issue.

¿Qué puntos me bloquean?

Ninguno hasta el momento.

**Comment by GabrielNicolao** [comment]
¿Qué hice la sesión anterior?

Reunión de grupo para organizarnos.

¿Qué voy hacer hoy?

El primer apartado.

¿Qué puntos me bloquean?

Ninguno

**Comment by ALexZhang1438** [comment]
- ¿Qué hice la sesión anterior?
Organización del grupo y la planificación del trabajo a realizar.
- ¿Qué voy hacer hoy?
Empezar con la primera historia.
- ¿Qué puntos me bloquean?
De momento nada ya que aun no hemos empezado la realización del trabajo.

**Comment by marcosagni98** [comment]
¿Qué hice la sesión anterior?

Hemos hecho una reunión de equipo

¿Qué voy hacer hoy?

Las tareas del issue

¿Qué puntos me bloquean?

Ninguno de momento

**Comment by DanielPacheco98** [comment]
¿Qué hice la sesión anterior?

Hicimos una reunión inicial para organizarnos y aclarar.

¿Qué voy hacer hoy?

Las tareas asignadas de la primera issue.

¿Qué puntos me bloquean?

Ninguno .

**Comment by GabrielBurgosLopez** [comment]
¿Qué hice la sesión anterior?

Hicimos una reunión para organizarnos.

¿Qué voy hacer hoy?

Las tareas asignadas del issue.

¿Qué puntos me bloquean?

Ninguno por ahora

**Comment by miguel93041** [comment]
¿Qué hice la sesión anterior?

Una reunión inicial para planificar el trabajo y organizarnos, además de elegir el SCRUM master.

¿Qué voy hacer hoy?

Las tareas asignadas de la primera issue.

¿Qué puntos me bloquean?

Ninguno por el momento.

**Comment by DaniLopezPina** [comment]
¿Qué hice la sesión anterior?

Mi Team1 hicimos una reunión para organizar el trabajo.

¿Qué voy hacer hoy?

Las tareas asignadas.

¿Qué puntos me bloquean?

Nada por ahora.

**Comment by cristiancardonamarin** [comment]
¿Qué hice la sesión anterior?
Organización del grupo, y ver los videos del primera tarea.
¿Qué voy a hacer hoy?
la siguiente tarea
¿Qué puntos me bloquean?
ninguno

**Comment by AlejandroCazcarra** [comment]
¿Qué hice la sesión anterior?

Reunión inicial para organizarnos

¿Qué voy hacer hoy?

Las tareas asignadas de la primera issue.

¿Qué puntos me bloquean?

Ninguno.

**Comment by SamuelMorales01** [comment]
- ¿Qué hice la sesión anterior?
Organización del grupo, planificación del trabajo a realizar y ver los videos de la primera tarea.

- ¿Qué voy a hacer hoy?
La siguiente tarea

- ¿Qué puntos me bloquean?
Ninguno por el momento

**Comment by bentalx** [comment]
¿Que hice la sesion anterior?

me reuni con mis compañeros para organizar el trabajo

¿Qué voy hacer hoy?

la tarea correspondiente a hoy

¿Qué puntos me bloquean?

hasta ahora ninguno

**Comment by Jorch00** [comment]
Qué hice la sesión anterior?
Organización del grupo y la planificación del trabajo a realizar.
¿Qué voy hacer hoy?
Empezar con la primera historia, pasarla a "in progress".
¿Qué puntos me bloquean?
De momento ninguno ya que aun no hemos empezado la realización del trabajo.

**Comment by albquintin** [comment]
Qué hice la sesión anterior?
Creamos un grupo y nos pusimos en contacto para organizar como vamos a trabajar
¿Qué voy hacer hoy?
La primera tarea de documentación
¿Qué puntos me bloquean?
Por ahora ninguno

**Comment by JorgeIba21** [comment]
Qué hice la sesión anterior?
Nos reunimos en grupo para organizarnos

¿Qué voy hacer hoy?
La primera tarea de documentación

¿Qué puntos me bloquean?
Ninguno

**Comment by gummielson** [comment]
¿Qué hice la sesión anterior?
Reunión de grupo.

¿Qué voy hacer hoy?
Primera tarea.

¿Qué puntos me bloquean?
Ninguno.

**Comment by CristianMarinGimenez** [comment]
¿Qué hice la sesión anterior?
Tuve una reunión con mi grupo para organizarnos

¿Qué voy hacer hoy?
Empezar con la primera tarea de documentacion

¿Qué puntos me bloquean?
Ninguno por el momento

**Comment by imartin24** [comment]
¿Qué hice ayer?
Reunion con los compañeros para aclarar dudas

¿Qué planeo hacer hoy?
Seguir con las tareas de documentación

¿Alguna duda?
Ninguna por ahora

**Comment by EBayego** [comment]
¿Qué hice la sesión anterior?

Organizar el trabajo e investigar como funciona

¿Qué voy hacer hoy?

La tarea de Welcome Board

¿Qué puntos me bloquean?

Ninguno por ahora.
