### ISSUE TITLE
Funcionamiento del panel Kanban

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#3]
> Si empiezas con esta tarea, pasa a la columna de "In progress"

A continuación te mostramos la documentación sobre el funcionamiento del panel kanban. Este panel es nuestra guía para conocer el estado de las tareas que tenemos que realizar en el proyecto en cada SPRINT y es obligatorio revisar el panel y las tareas todos los días (cada clase)

- [x] ¿Qué es un tablero? https://help.github.com/es/github/managing-your-work-on-github/about-project-boards
- [x] Cómo gestionar proyectos con kanban: https://www.youtube.com/watch?v=WP6Nt5XV980
- [x] Uso de kanban en otras industrias: https://www.youtube.com/watch?v=pbib2eGB7w0
- [x] Jerónimo Palacios, gurú de Kanban (es muy ameno y gracioso): https://www.youtube.com/watch?v=H4e5gKWJ04g

Cuando las tareas del panel estén completadas, tienes que pasarlas a "Done".

**Comment by oteromrt** [comment]
¿Qué hice ayer? 
Revisar los apartados de la sección "Welcome aboard", viendo tutoriales y explicaciones de las herramientas con las que vamos a contar para el proyecto.

¿Qué planeo hacer hoy?

Revisar la sección de Kanban y estudiar su contenido. 

¿Alguna duda?

De momento se va entendiendo que se planea hacer con estos tutoriales preparativos para la documentacion y realizacion del proyecto.

**Comment by slaptot** [comment]
> ¿Qué hice ayer?
> Revisar los apartados de la sección "Welcome aboard", viendo tutoriales y explicaciones de las herramientas con las que vamos a contar para el proyecto.
> 
> ¿Qué planeo hacer hoy?
> 
> Revisar la sección de Kanban y estudiar su contenido.
> 
> ¿Alguna duda?
> 
> De momento se va entendiendo que se planea hacer con estos tutoriales preparativos para la documentacion y realizacion del proyecto.

Good Job!!

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

Trabajé en la issue de "Las reglas del jeugo"

¿Qué voy hacer hoy?

Trabajar en la issue "Funcionamiento del panel Kanban"

¿Qué puntos me bloquean?

Ninguno hasta el momento.

**Comment by Jorch00** [comment]
¿Qué hice ayer?
Revisar los apartados de la sección "Funcionamiento del panel Kanban", viendo tutoriales y explicaciones.

¿Qué planeo hacer hoy?
Revisar la issue "las reglas del juego" y estudiar su contenido.

¿Alguna duda?
De momento se va entendiendo todo, por lo tanto niguna duda.

**Comment by marcosagni98** [comment]
¿Qué hice ayer?
Revisar el issue 1

¿Qué planeo hacer hoy?
Seguir trabajando en los issues

¿Alguna duda?
De momento no

**Comment by imartin24** [comment]
¿Qué hice ayer?
Terminar los tutoriales del Welcome aboard

¿Qué planeo hacer hoy?
Empezar con la tarea 3

¿Alguna duda?
Por el momento ninguna

**Comment by JorgeIba21** [comment]
¿Qué hice la sesión anterior?
Trabajar en la tarea anterior de las reglas del juego

¿Qué voy hacer hoy?
Realizar esta tarea

¿Qué puntos me bloquean?
Ninguno.

**Comment by slaptot** [comment]
> ¿Qué hice ayer?
> Revisar los apartados de la sección "Funcionamiento del panel Kanban", viendo tutoriales y explicaciones.
> 
> ¿Qué planeo hacer hoy?
> Revisar la issue "las reglas del juego" y estudiar su contenido.
> 
> ¿Alguna duda?
> De momento se va entendiendo todo, por lo tanto niguna duda.

Recuerda que las tareas del panel tienen que estar en “done” al final de la semana 😉

**Comment by slaptot** [comment]
> ¿Qué hice la sesión anterior?
> Trabajar en la tarea anterior de las reglas del juego
> 
> ¿Qué voy hacer hoy?
> Realizar esta tarea
> 
> ¿Qué puntos me bloquean?
> Ninguno.

Recuerda que las tareas del panel tienen que estar en “done” al final de la semana 😉

**Comment by slaptot** [comment]
> ¿Qué hice la sesión anterior?
> Trabajar en la tarea anterior de las reglas del juego
> 
> ¿Qué voy hacer hoy?
> Realizar esta tarea
> 
> ¿Qué puntos me bloquean?
> Ninguno.

Recuerda que las tareas del panel tienen que estar en “done” al final de la semana 😉

**Comment by ALexZhang1438** [comment]
- ¿Qué hice ayer?
Terminar la primera historia ( Welcome board - Antes de empezar #2 )

- ¿Qué planeo hacer hoy?
Terminar la segunda historia ( Funcionamiento del panel Kanban #3 )

- ¿Alguna duda?
Todo claro

**Comment by cristiancardonamarin** [comment]
¿Qué hice ayer?
Revisar y trabajar las reglas del juego
¿Qué planeo hacer hoy?
revisar funcionamiento del panel kanban
¿Alguna duda?
No

**Comment by AlejandroCazcarra** [comment]
¿Qué hice la sesión anterior?
Trabajar "Las reglas del juego"

¿Qué voy hacer hoy?
Revisar "Funcionamiento del panel Kanban"

¿Qué puntos me bloquean?
Ninguno

**Comment by EBayego** [comment]
¿Qué hice la sesión anterior?

Trabajar en la tarea de Las reglas del juego

¿Qué voy hacer hoy?

Trabajar en la tarea de Funcionamiento del panel Kanban

¿Qué puntos me bloquean?

De momento nada
