### ISSUE TITLE
Las reglas del juego - EDUSCRUM

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#4]
### PRIMEROS PASOS
• Una explicación inicial de eduScrum a los estudiantes (una vez - 2 horas).
• Definir el objetivo del Sprint, lo que significa objetivos de aprendizaje para ese Sprint,
• Definir y explicar los criterios de aceptación. Explicar claramente cuáles son los criterios que
determinan si un objetivo de aprendizaje se ha logrado para que los equipos puedan
comenzar a trabajar de forma independiente (experimentos, documentos, presentaciones,
etc.)
• Ayudar al Equipo de estudiantes: además de aclarar los objetivos de aprendizaje y los criterios
de aceptación también se refiere a la enseñanza y el material de referencia y a estar
disponible para preguntas.
• Supervisar que todos los involucrados sigan el proceso de eduScrum.

### ESTUDIANTES - GRUPOS
Los Equipos (4 personas y uno de ellos eduScrum Master) de estudiantes tienen las siguientes características:
1. Son autoorganizados. Nadie (ni siquiera el Propietario del producto) dice al Equipo de
estudiantes cómo deben conseguir los objetivos de aprendizaje.
2. Son multidisciplinares, con todas las habilidades necesarias y los temas de desarrollo
personal para poder alcanzar juntos los objetivos de aprendizaje y poderse desarrollar
personalmente.
3. Los miembros del Equipo de estudiantes pueden tener habilidades o áreas de enfoque
específicas, pero la responsabilidad recae en el Equipo de estudiantes en su conjunto.
4. Los miembros del Equipo de estudiantes pueden determinar ellos mismos si quieren
aportar sus cualidades o si quieren desarrollar nuevas áreas.
5. El Equipo de estudiantes sigue su propio progreso y el nivel de calidad en base a los
criterios de aceptación y la Definición de Terminado.

### EDUSCRUM MASTER
El eduScrum Master atiende al Propietario del producto (**PROFESOR**) de varias formas, entre ellas:

- Crea transparencia sobre el progreso al hacer que la "Hoja"	esté	disponible y asegurarse de que esté al día.
- Facilita	los	eventos	de	eduScrum	cuando	se	le	solicite	o	necesite.

El eduScrum Master atiende al Equipo de estudiantes de varias formas, entre ellas:
- Crea	transparencia	sobre	el	progreso	al	hacer	que	la	"Hoja"	esté	disponible	y	asegurarse	
de	que	esté al	día.
- Asegura	la	correcta	ejecución	de	eduScrum	(inicia	y	facilita	los eventos	de	eduScrum,	
ejecuta	los	eventos	correctamente,	utiliza	los	instrumentos	correctamente).
- Facilita	la	colaboración	entre	los	equipos.

### SPRINT
Los Sprints consisten en:
• Reunión de Planificación del Sprint, incluyendo la formación del equipo.
• Reunión de pie al inicio de	cada clase.
• Realizar la asignaciones y tareas dentro de un Sprint.
• Revisión del Sprint.
• Retrospectiva del Sprint y reflexión personal.

Durante el Sprint:
• La	composición del Equipo de estudiantes no se cambia.
• El alcance no se cambia; la calidad se puede aclarar y renegociar entre el Propietario del 
producto y el Equipo de estudiantes a medida que se aprende.

El Sprint finaliza con una Revisión y una Retrospectiva, inspeccionando el trabajo entregado e 
identificando posibilidades de mejora.

### REUNIÓN PLANIFICACIÓN SPRINT
La reunión de Planificación del Sprint se planifica al inicio del Sprint. Se compone de 3 elementos ;
**formación del Equipo**, **objetivos de aprendizaje** y **planificación del trabajo**

### REUNIÓN DE PIE
Antes de cada clases, se tiene que enviar o rellenar un Google Docs, dirigido al Propietario del producto (Profesor) con las siguientes preguntas:
- ¿Qué	he	hecho	para	ayudar	al	Equipo a	conseguir	el	objetivo del	Sprint desde	la	clase	anterior?
- ¿Qué	voy	a	hacer	en esta	clase	para	ayudar	al	Equipo a	conseguir	el	objetivo del	Sprint? 
- ¿Cuáles	son	los	impedimentos	que	obstaculizan	al Equipo o	a	mí para	lograr	el	objetivo del	Sprint?

### RETROSPECTIVA
La Retrospectiva del Sprint consta de tres partes:
1. Los estudiantes evalúan las metodologías y métodos de trabajo del equipo e identifican
puntos de mejora;
2. A continuación, cada alumno evalúa a los miembros de su equipo sobre las habilidades
y puntos de mejora, y se evalúa también a si mismo;
3. El equipo debate sobre lo que deberían dejar de hacer.

**Comment by slaptot** [comment]
¿Qué hice la sesión anterior?
Vimos el video de Alberto y nos juntamos en grupos.

¿Qué voy hacer hoy?
Voy a trabajar este ticket

¿Qué puntos me bloquean?
No entiendo que dice el videotutorial de SCURM

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

Trabajé la issue de Welcome board.

¿Qué voy hacer hoy?

Trabajar sobre la issue de las reglas del juego.

¿Qué puntos me bloquean?

Ninguno hasta el momento.

**Comment by Obistto** [comment]
¿Qué hice la sesión anterior?

La primera tarjeta.

¿Qué voy hacer hoy?

La segunda (las reglas del juego).

¿Qué puntos me bloquean?

Ninguno.

**Comment by albquintin** [comment]
**¿Qué hice la sesión anterior?**
Revisamos el material de la tarea "Welcome board"
**¿Qué voy hacer hoy?**
Revisar el material de la tarea "Las reglas del juego"
**¿Qué puntos me bloquean?**
Por ahora ninguno

**Comment by slaptot** [comment]
@SalesianosZaragoza/team1_1h @SalesianosZaragoza/team2_1h @SalesianosZaragoza/team3_1h @SalesianosZaragoza/team4_1h @SalesianosZaragoza/team5_1h @SalesianosZaragoza/team6_1h —> Os recuerdo que el próximo lunes tienen que estar las tareas del panel finalizadas, es decir tenéis que haber leído y visto los vídeos de cada una. No se va a realizar ninguna prueba, pero lo que aprendáis en estas 2 semanas os servirá en el siguiente sprint(que empieza el próximo lunes). Voy leyendo vuestros comentarios de reunión diaria, buen trabajo chicos, lo estáis haciendo genial!! Cualquier duda podéis mandarme un email a: Alberto.munoz@zaragoza.salesianos.edu Ánimo que vais entendiendo la forma de trabajó scrum!! 👍

**Comment by seroal99** [comment]
¿Qué hice la sesión anterior?
Revisar funcionamiento del panel kanban
¿Qué voy hacer hoy?
Revisar tarea "Las reglas del juego"
¿Qué puntos me bloquean?
ninguno

**Comment by AlejandroCazcarra** [comment]
¿Qué hice la sesión anterior?
Revisar la primera tarea
¿Qué voy hacer hoy?
Las reglas del juego
¿Qué puntos me bloquean?
Ninguno

**Comment by ALexZhang1438** [comment]
- ¿Qué hice la sesión anterior?

Finalizar la segunda historia (Funcionamiento del panel Kanban #3)

- ¿Qué voy hacer hoy?

Terminar la tercera historia (Las reglas del juego - EDUSCRUM #4)

- ¿Qué puntos me bloquean?

Todo claro

**Comment by SamuelMorales01** [comment]
¿Qué hice la sesión anterior?
Finalizar la segunda historia (Funcionamiento del panel Kanban #3)

¿Qué voy hacer hoy?
Terminar la tercera historia (Las reglas del juego - EDUSCRUM #4)

¿Qué puntos me bloquean?
Ninguno

**Comment by andres11dmg** [comment]
¿Qué hice la sesión anterior?
Realizar las historia de las reglas del juego
¿Qué voy hacer hoy?
Empezar la historia NPM
¿Qué puntos me bloquean?
Poca adaptacion a la pagina

**Comment by Jorch00** [comment]
¿Qué hice la sesión anterior?

Trabajé la issues del panel Kanban y las reglas del juego.

¿Qué voy hacer hoy?

Trabajar sobre la issue de NPM

¿Qué puntos me bloquean?

Ninguno hasta el momento.

**Comment by slaptot** [comment]
@andres11dmg 
> ¿Qué hice la sesión anterior?
> Realizar las historia de las reglas del juego
> ¿Qué voy hacer hoy?
> Empezar la historia NPM
> ¿Qué puntos me bloquean?
> Poca adaptacion a la pagina

Buenas,
¿A que te refieres con poca adaptación a la página?
