### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#5]
NPM es un repositorio de software, que se usa en proyectos Web. A continuación te dejamos varios sitios web y tutoriales online para que entiendas su funcionamiento:
- [x] [npm se une a github](https://github.blog/2020-04-15-npm-has-joined-github/)
- [x] [Documentación NPM](https://docs.npmjs.com/)
- [x] [Instalación de npm y de NodeJS](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
- [x] [Video sobre NPM](https://www.youtube.com/watch?v=4aNA8ZHihFE)
- [x] [Crear un package.json](https://docs.npmjs.com/creating-a-package-json-file)

**Comment by GabrielNicolao** [comment]
¿Qué hice la sesión anterior?

Trabaje la tarea de "Funcionamiento del panel Kanban".

¿Qué voy hacer hoy?

Trabajar en la tarea "NPM"

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

Trabaje la issue de "Funcionamiento del panel Kanban".

¿Qué voy hacer hoy?

Trabajar en la issue "NPM", instalando Node.js y NPM

¿Qué puntos me bloquean?

Hasta ahora ninguno, aunque la instalación es un poco liosa.

**Comment by Obistto** [comment]
¿Qué hice la sesión anterior?

Trabaje la tarea de funcionamiento del panel Kanban.

¿Qué voy hacer hoy?

Terminar las issues.

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by seroal99** [comment]
¿Qué hice la sesión anterior?

Trabaje la tarea de las reglas del juego

¿Qué voy hacer hoy?

hacer la tarea npm

¿Qué puntos me bloquean?

ninguno

**Comment by slaptot** [comment]
@JavierFananasNaya Si tienes alguna duda de la instalación, házmela llegar por correo o por comentario en github (pones @slaptot y lo recibo en el acto ;)). Recuerda en el equipo y a los otros equipos que tenéis que pasar las tareas que hayáis "completado" (leído y visualizado los videos) a la columna "Done". Lo estáis haciendo genial, vamos!

**Comment by AlejandroCazcarra** [comment]
¿Qué hice la sesión anterior?
Trabajar"Funcionamiento del panel Kanban".

¿Qué voy hacer hoy?
Trabajar en la tarea "NPM" e instalar NPM y Node.js

¿Qué puntos me bloquean?
Ninguno

**Comment by SamuelMorales01** [comment]
¿Qué hice la sesión anterior?
Trabajar con funcionamiento del panel kanban.

¿Qué voy hacer hoy?
Trabajar en la tarea "NPM" e instalar NPM y Node.js

¿Qué puntos me bloquean?
Ninguno hasta el momento

**Comment by JorgeIba21** [comment]
¿Qué hice la sesión anterior?
La tarea de funcionamiento del panel kanban

¿Qué voy hacer hoy?
Las tareas NPM y Node.js

¿Qué puntos me bloquean?
Ninguno.

**Comment by albquintin** [comment]
¿Qué hice la sesión anterior?
El funcionamiento del Panel kanban

¿Qué voy hacer hoy?
Las tareas de NPM y Node.js

¿Qué puntos me bloquean?
De momento ninguno

**Comment by ALexZhang1438** [comment]
- ¿Qué hice la sesión anterior?

Terminar la tercera historia (Las reglas del juego - EDUSCRUM #4)

- ¿Qué voy hacer hoy?

Terminar la historia de NPM

- ¿Qué puntos me bloquean?

todo claro

**Comment by cristiancardonamarin** [comment]
¿Qué hice la sesión anterior?
 trabajar el funcionamiento del panel Kanban
¿Qué haré hoy?
trabajar en NPM
¿Puntos que me bloquean?
ninguno

**Comment by EBayego** [comment]
¿Qué hice la sesión anterior?

Trabajar en la tarea del Funcionamiento del panel Kanban

¿Qué voy hacer hoy?

Trabajar en la tarea de "NPM"

¿Qué puntos me bloquean?

Nada, de momento
