### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#6]
Node.js es un entorno de tiempo de ejecución. ⭐ Es código abierto de JavaScript para la creación de aplicaciones de red a tiempo real. ✅ Ligero y escalable.
Node.js es un entorno de tiempo de ejecución que está diseñado para generar aplicaciones web de forma altamente optimizada. Desde su nacimiento en el año 2009 ha logrado convertirse en una tecnología a considerar en el desarrollo web.

### Gestor de librerías Node Package Manager
Uno de los puntos fuertes de nodeJS es su [Node Package Manager]( #5) (un los paquetes NPM). Una especie de gestor que da acceso a un conjunto de librerías muy extenso que además son gratuitas y generadas a partir de la colaboración de los usuarios de su comunidad. Algunos de los paquetes más conocidos que podrás encontrar en su plataforma son React, Gulp, Browserify, Grunt-cli, Bower, Grunt, Express, Cordova o Forever. (Podrás obtener más información accediendo a su página oficial en npmjs.org).

### ¿Por qué utilizar NodeJS?

1. Se trata de un lenguaje que puede utilizarse en la gran mayoría de servidores, incluyendo los más conocidos como Unix/Linux, Microsoft o Mac.
2. Una buena parte de las plataformas más eficiente y mejor optimizadas de la red como por ejemplo Linkedin o Paypal fueron desarrolladas a partir de NodeJS, las cuales son fieles indicadores de calidad y potencialidad.
3. Garantiza un elevado rendimiento. No sólo puede generar arquitecturas sólidas y potentes sino que además reduce de una forma muy drástica el ratio de errores.
4. Cualquier programador que haya programado en JavaScript no tendrá mucho problema con NodeJS.
5. Su alta capacidad de escalabilidad ha llevado el mundo de la programación a un nuevo nivel. Hoy en día los desarrolladores pueden generar aplicaciones potentes y con una capacidad escalable asombrosa. Pero, ¿esto en qué se traduce? En aplicaciones web con potencialidades sorprendentes como semánticas que permiten miles y miles de solicitudes a un único servidor de forma simultánea. Esto ha permitido multiplicar las capacidades de las aplicaciones web que hasta entonces podían soportar hasta un máximo de cuatro mil usuarios por servidor. Sin embargo NodeJS ha permitido multiplicar la capacidad para alojar usuarios activos en las aplicaciones y sin necesidad de incrementar la infraestructura de servidores.
6. Es quizá la opción más competitiva para diseñar aplicaciones que gestionen grandes cantidades de información generadas por una comunidad elevada de usuarios. Un buen ejemplo sería Facebook, una plataforma en la que se generan cientos de miles de comentarios y contenidos por cada segundo.
7. No sólo el funcionamiento de las aplicaciones resulta mucho más ágil y potente, sino que además el proceso de desarrollo y programación también resulta mucho más liviano y rápido. Al final estamos hablando de aplicaciones ideales a nivel de experiencia para los usuarios. Uno de los factores determinantes es que NodeJS trabaja mediante el motor V8 de Google. El motor V8 de Google ha sido generado para funcionar dentro de un navegador y poner en marcha el código JavaScript con una velocidad asombrosa. NodeJS está planteado de tal modo que puede efectuar perfectamente el V8 de Google desde el lado del servidor. Esto abre un nuevo abanico de posibilidades y permite que se desarrolle un casi infinito conjunto de librerías que actúan casi como un nuevo ecosistema NodeJS.
8. Gracias a que NodeJS permite trabajar tanto desde el servidor como desde el cliente, es posible generar una transferencia de información mucho más rápida e inmediata. El resultado de todo esto es una reducción considerable en los periodos de trabajo.
9. Debido a sus altas prestaciones para gestionar y procesar grandes volúmenes simultáneos de información, NodeJS es una opción estrella para el desarrollo de aplicaciones como chats online o juegos interactivos.
10. Está diseñado para incentivar el intercambio entre usuarios y programadores: Ha desarrollado una comunidad bastante amplia que permite establecer lazos de colaboración muy interesantes desde diferentes ópticas lo cual resulta muy enriquecedor para los desarrolladores. Además al ser un lenguaje popular y empleado por profesionales de todo el mundo resulta fácil encontrar información y recursos en Internet.

### ¿Qué usos reales se le da a nodejs?
Es una herramienta genial para todo tipo de cosas. Aplicaciones web, aplicaciones en línea de comandos, scripts para administración de sistemas, todo tipo de aplicaciones de red, etc.

Es rápido, muy rápido. Y esto es importante por varias razones: El desarrollo es más rápido, la ejecución de tests de unidad se puede hacer más rápido, las aplicaciones son más rápidas y por tanto la experiencia de usuario es mejor y menor coste de infraestructura.

A continuación te dejamos varios sitios web y tutoriales online para que entiendas su funcionamiento:
- [x] [documentación nodejs](https://nodejs.org/es/docs/)
- [x] [Video como instalar nodejs en windows](https://www.youtube.com/watch?v=y4SY6ReRQLQ)
- [x] [Instalación de npm y de NodeJS](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)

**Comment by Obistto** [comment]
¿Qué hice la sesión anterior?

Trabaje la tarea de npm.

¿Qué voy hacer hoy?

Terminar node.

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

Trabaje la issue de "NPM" e instale NPM y Node.js.

¿Qué voy hacer hoy?

Realizar una pequeña reunión con el equipo y poner en común dudas y complicaciones que tenemos, después trabajaré la issue de "Node.js"

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by ALexZhang1438** [comment]
- ¿Qué hice la sesión anterior?

Documentado e instalación de NPM.

- ¿Qué voy hacer hoy?

Documentación Node.js  

- ¿Qué puntos me bloquean?

Nada todo claro

**Comment by EBayego** [comment]
¿Qué hice la sesión anterior?

Trabajar en la tarea de NPM

¿Qué voy hacer hoy?

Trabajar en la tarea de Node.js

¿Qué puntos me bloquean?

Hasta ahora ninguno

**Comment by SamuelMorales01** [comment]
¿Qué hice la sesión anterior?

Trabaje la tarea de "NPM" e instale NPM y Node.js.

¿Qué voy hacer hoy?

Trabajaré la tarea de "Node.js"

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by JorgeIba21** [comment]
¿Qué hice la sesión anterior?
La tarea de NPM

¿Qué voy hacer hoy?
La tarea de Node.js

¿Qué puntos me bloquean?
Ninguno.

**Comment by seroal99** [comment]
Qué hice la sesión anterior?
Documentacion e instalación de NPM

¿Qué voy hacer en esta sesion?
Documentación Node.js

¿Qué puntos me bloquean?
Ninguno de momento

**Comment by miguel93041** [comment]
Qué hice la sesión anterior?
Terminar el Issue de JHipster

¿Qué voy hacer en esta sesion?
Terminar el Issue de Nodejs

¿Qué puntos me bloquean?
Ninguno de momento
