### ISSUE TITLE
JHipster

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#7]
### ¿Qué es JHipster?
Es un completo stack de tecnologías preparadas para ser usadas mediante unos simples comandos. Esto nos permite empezar proyectos que tienen parte de servidor (base de datos, servidor web, API...) y la parte Frontal (Angular 9, bootstrap, SCSS...).

## Single Web page application:

- Angular or React or Vue
- Responsive Web Design with Twitter Bootstrap
- HTML5 Boilerplate
- Compatible with modern browsers (Chrome, FireFox, Microsoft Edge…)
- Full internationalization support
- Optional Sass support for CSS design
- Optional WebSocket support with Spring Websocket

With the great development workflow:

- Installation of new JavaScript libraries with NPM
- Build, optimization and live reload with Webpack
- Testing with Jest and Protractor
And what if a single Web page application isn’t enough for your needs?
- Support for the Thymeleaf template engine, to generate Web pages on the server side

### Technology stack on the server side
A complete Spring application:

Spring Boot for application configuration

- Maven or Gradle configuration for building, testing and running the application
- “development” and “production” profiles (both for Maven and Gradle)
- Spring Security
- Spring MVC REST + Jackson
- Optional WebSocket support with Spring Websocket
- Spring Data JPA + Bean Validation
- Database updates with Liquibase
- Elasticsearch support if you want to have search capabilities on top of your database
- MongoDB and Couchbase support if you’d rather use a document-oriented NoSQL database instead of JPA
- Cassandra support if you’d rather use a column-oriented NoSQL database instead of JPA
- Kafka support if you want to use a publish-subscribe messaging system

### Listado de enlaces y tutoriales
- [x] [Página Oficial JHipster](https://www.jhipster.tech/)
- [x] [Stack tecnológico](https://www.jhipster.tech/tech-stack/)
- [x] [Iniciar aplicación con JHipster](https://www.youtube.com/watch?v=nDMlNo3lFZk)
- [x] [Crear entidades](https://www.youtube.com/watch?v=C-4n-ni-buw)

**Comment by JavierFananasNaya** [comment]
¿Qué hice la sesión anterior?

Trabajé la issue de "Node.js"

¿Qué voy hacer hoy?

Trabajaré la issue de "Jhipster" y por lo tanto terminaré el primer Sprint.

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by GabrielNicolao** [comment]
¿Qué hice la sesión anterior?

Terminé la tarea "NPM".

¿Qué voy hacer hoy?

Completar la tarea "JHipster".

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by slaptot** [comment]
@SalesianosZaragoza/team1_1h @SalesianosZaragoza/team2_1h @SalesianosZaragoza/team3_1h @SalesianosZaragoza/team4_1h @SalesianosZaragoza/team5_1h @SalesianosZaragoza/team6_1h 
Recordar que el sprint acaba el próximo lunes, y ese mismo día empieza el siguiente Sprint. Haremos una retrospectiva que consistirá en rellenar un formulario en la que podamos conocer qué hemos hecho bien, que podemos mejorar y que no ha salido bien. Necesito que cada "líder" de cada equipo le dé a me gusta a este comentario para conocer que lo habéis visto todos. 

Un saludo!

**Comment by marcosagni98** [comment]
¿Qué hice la sesión anterior?

Trabaje en todos los issues que nos faltaban

¿Qué voy hacer hoy?

Terminar jhipster

¿Qué puntos me bloquean?

Hasta ahora ninguno.

**Comment by bentalx** [comment]
¿Qué hice la sesión anterior?

profundizar en jhipster

¿Qué voy a hacer hoy?

terminar el primer sprint

¿Qué puntos me bloquean?

Hasta ahora ninguno

**Comment by DaniLopezPina** [comment]
¿Qué hice la sesión anterior?

Termine y trabaje en los 'issues' que me faltaban (NPM, Node.js)

¿Qué voy hacer hoy?

La ultima 'issue' de jHipster 

¿Qué puntos me bloquean?

Nada.

**Comment by calvo59** [comment]
¿Qué hice la sesión anterior?

Terminar todas las 'issues' que me faltaban.

¿Qué voy a hacer hoy?

Terminar el  primer sprint.

¿Qué puntos me bloquean?

Por ahora ninguno.

**Comment by EBayego** [comment]
¿Qué hice la sesión anterior?

Trabajar en la tarea de Node.js

¿Qué voy hacer hoy?

Trabajar en la tarea de JHipster para finalizar

¿Qué puntos me bloquean?

Ninguno

**Comment by ALexZhang1438** [comment]
- ¿Qué hice la sesión anterior?

Documentación sobres Node.js 

- ¿Qué voy hacer hoy?

Terminar la documentación sobres JHipster  

- ¿Qué puntos me bloquean?

todo claro.

**Comment by SamuelMorales01** [comment]
¿Qué hice la sesión anterior?

Trabajar en la tarea de Node.js

¿Qué voy hacer hoy?

Trabajar en la tarea de JHipster para terminar

¿Qué puntos me bloquean?

Ninguno

**Comment by Jorch00** [comment]
Qué hice la sesión anterior?
Terminé la issue de "Node.js" y NPM

¿Qué voy hacer hoy?
Trabajaré la issue de "Jhipster" y por tanto terminaré el primer Sprint.

¿Qué puntos me bloquean?
Hasta ahora ninguno.

**Comment by JorgeIba21** [comment]
¿Qué hice la sesión anterior?
Trabajar la tarea de Node.js

¿Qué voy hacer hoy?
Trabajar la tarea JHipster 

¿Qué puntos me bloquean?
Ninguno.

**Comment by cristiancardonamarin** [comment]
¿Qué hice la sesión anterior?
la tarea Node.js

¿Qué voy hacer hoy?
el trabajo de JHipster

¿Qué puntos me bloquean?
Ninguno.

**Comment by oteromrt** [comment]
¿Qué hice en la sesion anterior?
 EL issue Node.js

¿Qué voy a hacer hoy?

Trabajar en el issue de JHipster

¿Qué puntos me bloquean?

De momento no hay problemas con el progreso

**Comment by miguel93041** [comment]
¿Qué hice la sesión anterior?
Trabajar en algunos issues que me faltaban.

¿Qué voy hacer hoy?
Terminar el Issue de JHipster

¿Qué puntos me bloquean?
Ninguno.

**Comment by seroal99** [comment]
¿Qué hice la sesión anterior?
Trabajar tarea node.js
voy hacer hoy?
Terminar  JHipster

¿Qué puntos me bloquean?
Ninguno.

**Comment by albquintin** [comment]
¿Qué hice la sesión anterior?
Buscar información sobre node.js y npm e instalarlas.

¿Qué voy hacer hoy?
Ver como funciona JHipster y terminar la tarea.

¿Qué puntos me bloquean?
Algunas de las tecnologías que se usan en JHipster no las he dado y no las comprendo bien, y no acabo de ver como funciona todo.

**Comment by slaptot** [comment]
@albquintin es normal que no se entiendan todas las tecnologías, tenéis que pensar que lo importante es tener la “foto completa” de todas las tecnologías implicadas que en el siguiente sprint vamos a usar. Muy bien por el comentario👏
