### ISSUE TITLE
Retrospectiva Sprint 1

### ISSUE THREAD

**Issue by slaptot** [SalesianosZaragoza/ScrumEDD#8]
### **Lo primero... !Felicidades a todos!** 
Habéis entendido las reglas del juego y por mi parte y desde la distancia que nos obliga, creo que os habéis organizado y aprendido según lo que os pedía. 

Este proceso, llevado a un nivel más amplio será lo que os encontréis cuando accedáis al mercado laboral, es por eso que lo importante es auto organizaros y seguir las instrucciones de vuestros colegas de trabajo.

Mañana, cuando todos los equipos rellenen el formulario os mandare los resultados para que todos podáis analizar lo sucedido en otros equipos, es importante que aprendamos entre todos.

A lo largo de esta semana os mandare por medio de Gorka la segunda parte del video que será la simulación del "kickstart" del proyecto. Como si fuese el Project Manager de la empresa, os contaré lo que hay que hacer y os añadiré en el panel las nuevas tareas. **Are you ready?**

![Choca los 5](https://media.giphy.com/media/mHEes6Quf8XK0/source.gif)

**Comment by slaptot** [comment]
Os pongo los resultados, si no me equivoco falta el grupo @SalesianosZaragoza/team1_1h si podéis avisarles para que lo pongan:

### **¿Qué hicimos bien? Responde con los aspectos que consideres que han ido bien.**

- Mantener una **buena comunicación grupal** y aprender tecnologías nuevas.

- En el grupo 4 consideramos que hemos realizado todas las tareas y sin muchos problemas.

- Somos el Team 3.
Creamos un **grupo de whatsApp** y nos organizamos desde el primer día.
Resumirnos el contenido por el grupo y aclararnos las dudas en grupo.

- Hacer el trabajo a tiempo, que nos ayudamos unos a otros y **buena sincronización** en el equipo.(Team 6)

- EL EQUIPO 5 realizamos las issues del Sprint a buen ritmo, repartiéndolas a lo largo de la duración del Sprint y organizándonos todos los días por **mensajes privados** y algunas reuniones por **Discord**. Administramos bien el tiempo de duración de cada tarea.

### **CONCLUSIONES**
Los equipos han sabido comunicarse entre los miembros y se ha sabido repartir tareas para agilizar el proceso. Me gusta el uso de sistemas de mensajería poco comunes y que permiten audio en tiempo real

**Comment by slaptot** [comment]
### **¿Qué queremos mejorar? Responde con las cosas que piensas que pueden mejorar**

- EL tiempo de respuesta ante cambios imprevistos.

- En el grupo 4 queremos mejorar la comunicación y **coordinación** del grupo.

- Dejamos las cosas para la última semana y queremos **organizarnos** mejor en ese aspecto.

- Aprender mas de jhipster y Nodejs.

- La **comunicación** del grupo por parte de algunos miembros no ha sido la ideal, deberíamos mejorar el grado de **compromiso individual** con el proyecto.

### **CONCLUSIONES**
Aunque en la pregunta anterior habéis mostrado que la organización fue una de las mejores cosas que se ha hecho, ahora planteáis mejorarlo. La planificación de tareas es el eterno estigma de los informáticos, y siempre lo vais a llevar en vuestras espaldas como parte de vuestro ADN. Buscar soluciones de planificación, por ejemplo midiendo las tareas al principio, sacando su complejidad por tamaños: **S, M, L o XL** por ejemplo.

**Comment by slaptot** [comment]
### **¿Qué problemas tuvimos? Responde con las cosas que no han resultado bien o que no se han entendido correctamente**

- Es **todo nuevo** para nosotros, somos el equipo 2 y lo nuevo siempre cuesta. JHipster nos ha resultado un poco dificil de entender.

- En el grupo 4, algún problema al crear en npm el servidor web. **No se comprendía** bien del todo el funcionamiento de JHipster.

- **Documentación complicada, dificil de asimilar** a la primera y falta documentación visual dónde se pueda ver facilmente de que es capaz la tecnología.

- instalacion de jhipster:
A alguno de nuestro equipo le **daba error** al instalar y configurarlo.
a otro windows no le permitía instalarlo de ninguna manera al sospechar que era un archivo potencialmente peligroso (saltaba el antivirus y el smartScreen al instalar el Yarn).

- EL EQUIPO 5 **tuvimos algunas dificultades** con el proceso de instalación de algunos de los programas de las últimas issues, pero lo conseguimos solucionar dentro de los plazos estimados. El otro problema que nos encontramos fue la coordinación de los miembros para hacer las tareas en el tiempo asignado.

### **CONCLUSIONES**
El fallo, el problema, las dificultades, complejidades... es parte de lo que se tiene que aprender y creo que lo habéis hecho fenomenal. No tener problemas puede ser por 2 cosas, o que sois el futuro CTO de Google (estaría bien ¿ehh? 😉) o que no lo habéis intentado. El trabajo es la base de vuestro futuro profesional y los retos ante cambios es enorme en el sector, frustración ante nuevos lenguajes, nuevas formas de trabajar... todo os hace crecer diariamente. 

¡¡¡MUY BIEN HECHO!!!

![Good Job](https://media.giphy.com/media/kigLtfDrV3K9N0wYCO/source.gif)

**Comment by JoTerrance** [comment]
@SalesianosZaragoza/1h check this retrospectiva analysis, enjoy, and thank you for playing this game :+1:
